### PR TITLE
Value set domain updated

### PR DESCRIPTION
**Pull request by Jungyubw**

### CODE REVIEW

**Comment by maxence-lefort** [comment]
@Jungyubw in ValuesetServiceImpl.java the removeAll method isn't implemented (or at least it's empty), is it on purpose?

**Comment by maxence-lefort** [comment]
*removeCollection not removeAll

**Comment by Jungyubw** [comment]
Oh.. I missed it.
I have pushed it.


On Mar 6, 2018, at 10:09 AM, Maxence LEFORT <notifications@github.com<mailto:notifications@github.com>> wrote:


*removeCollection not removeAll

**Comment by maxence-lefort** [comment]
@Jungyubw thanks, can I delete the branch?

**Comment by Jungyubw** [comment]
Sure. Thanks.
On Mar 6, 2018, at 10:20 AM, Maxence LEFORT <notifications@github.com<mailto:notifications@github.com>> wrote:


@Jungyubw<https://github.com/jungyubw> thanks, can I delete the branch?

**Pull request merged**
