### PR TITLE
Feature/multiplefixes

### PR DESCRIPTION
**Pull request by Abdelghani90**

### CODE REVIEW

**Comment by haffonist** [comment]
@Abdelghani90 please fix the conflict.

**Comment by Abdelghani90** [comment]
@Jungyubw @HossamT please review

**Comment by Jungyubw** [comment]
I have reviewed TreeTable and Conformance Statements.

It looks good for me. Thanks.

**Comment by Jungyubw** [comment]
I have push quick fix to load comparison complement.

**Pull request merged**
